"use client";
import { usePathname } from "next/navigation"; // New hook
// import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/page";
import TopBar from "@/components/top-bar/page";

const inter = Inter({subsets: ["latin"]});

// export const metadata: Metadata = {
//   title: "Okey Mart",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 const pathname = usePathname(); // Replaces useRouter()

 // Define pages where you want to hide TopBar and Footer
 const hiddenPages = ["/signin", "/signup", "/forgotten_password"];

 // Check if the current path matches any of the hidden pages
 const hideLayout = hiddenPages.includes(pathname);

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
      </head>
      <body>
        <div className="page-container">
          {/* Conditionally render TopBar */}
          {!hideLayout && <TopBar />}
          <div className={`${inter.className} content`}>{children}</div>
        </div>
        {/* Conditionally render Footer */}
        {!hideLayout && <Footer />}
      </body>
    </html>
  );
}
